"""Initial tables - haberler

Revision ID: faf635f8d1be
Revises: 
Create Date: 2026-01-17 23:37:33.653468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf635f8d1be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haberler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=500), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('flash_ozet', sa.Text(), nullable=True),
    sa.Column('detayli_ozet', sa.Text(), nullable=True),
    sa.Column('tam_metin', sa.Text(), nullable=True),
    sa.Column('kaynak_url', sa.String(length=1000), nullable=True),
    sa.Column('kaynak_adi', sa.String(length=200), nullable=True),
    sa.Column('yazar', sa.String(length=200), nullable=True),
    sa.Column('yayin_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_skor', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('anahtar_kelimeler', sa.JSON(), nullable=True),
    sa.Column('okunma_sayisi', sa.Integer(), nullable=True),
    sa.Column('tam_metin_acilma', sa.Integer(), nullable=True),
    sa.Column('ai_islendi', sa.Integer(), nullable=True),
    sa.Column('yayinda', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_haberler_id'), 'haberler', ['id'], unique=False)
    op.create_index(op.f('ix_haberler_kategori'), 'haberler', ['kategori'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_haberler_kategori'), table_name='haberler')
    op.drop_index(op.f('ix_haberler_id'), table_name='haberler')
    op.drop_table('haberler')
    # ### end Alembic commands ###
